---
- name: Create a resource group
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - ../vars/aap_survey.yml

  tasks:
    - name: Create a resource group
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"

- name: Create a virtual network
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - ../vars/aap_survey.yml

  tasks:
    - name: Create a virtual network
      azure.azcollection.azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: "{{ virtual_network }}"
        address_prefixes_cidr: "{{ virtual_network_prefix }}"

- name: Create s network security group with SSH and RDP access
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - ../vars/aap_survey.yml

  tasks:
    - name: Create a network security group with SSH and RDP access
      azure.azcollection.azure_rm_securitygroup:
        resource_group: "{{ resource_group }}"
        name: "{{ network_security_group }}"
        purge_default_rules: true
        purge_rules: true
        rules:
          - name: Allow-SSH
            protocol: Tcp
            access: Allow
            priority: 1000
            direction: Inbound
            source_address_prefix: '*'
            source_port_range: '*'
            destination_address_prefix: '*'
            destination_port_range: 22
            description: Allow SSH access from any source
          - name: Allow-RDP
            protocol: Tcp
            access: Allow
            priority: 1001
            direction: Inbound
            source_address_prefix: '*'
            source_port_range: '*'
            destination_address_prefix: '*'
            destination_port_range: 3389
            description: Allow RDP access

- name: Create a subnet
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - ../vars/aap_survey.yml

  tasks:
    - name: Create a subnet
      azure.azcollection.azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: "{{ subnet }}"
        address_prefix: "{{ subnet_address_prefix }}"
        virtual_network: "{{ virtual_network }}"
        security_group: "{{ network_security_group }}"

- name: Create a Windows virtual machine with an interface
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - ../vars/aap_survey.yml

  tasks:
    - name: Create a network interface
      azure.azcollection.azure_rm_networkinterface:
        resource_group: "{{ resource_group }}"
        name: "{{ network_interface }}"
        virtual_network: "{{ virtual_network }}"
        subnet_name: "{{ subnet }}"
        security_group: "{{ network_security_group }}"
        create_with_security_group: false
        ip_configurations:
          - name: ipconfig1
            public_ip_address_name: demo_public_ip
            primary: true

    - name: Create Windows virtual machine
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
        name: "{{ vm_name }}"
        vm_size: "{{ vm_size }}"
        admin_username: "{{ vm_admin_username }}"
        admin_password: "{{ vm_admin_password }}"
        network_interfaces: "{{ network_interface }}"
        os_type: Windows
        image:
          offer: WindowsServer
          publisher: MicrosoftWindowsServer
          sku: 2022-Datacenter
          version: latest
        os_disk_name: demo_os_disk
        os_disk_size_gb: 128
        os_disk_caching: ReadWrite
        managed_disk_type: Standard_LRS
      register: result

    - ansible.builtin.debug:
        msg: "{{ result }}"
...


# "ansible_facts": {
#     "azure_vm": {
#         "etag": "\"2\"",
#         "hardware_profile": {
#             "vm_size": "Standard_D2s_v3"
#         },
#         "id": "/subscriptions/00b0a591-c96c-4b2f-bf7e-0c04a300756d/resourceGroups/demo_resource_group/providers/Microsoft.Compute/virtualMachines/demo-vm",
#         "instance_view": {
#             "disks": [
#                 {
#                     "name": "demo_os_disk",
#                     "statuses": [
#                         {
#                             "code": "ProvisioningState/succeeded",
#                             "display_status": "Provisioning succeeded",
#                             "level": "Info",
#                             "time": "2025-04-14T04:21:49.676047Z"
#                         }
#                     ]
#                 }
#             ],
#             "hyper_v_generation": "V1",
#             "statuses": [
#                 {
#                     "code": "ProvisioningState/succeeded",
#                     "display_status": "Provisioning succeeded",
#                     "level": "Info",
#                     "time": "2025-04-14T04:22:40.894759Z"
#                 },
#                 {
#                     "code": "PowerState/running",
#                     "display_status": "VM running",
#                     "level": "Info"
#                 }
#             ],
#             "vm_agent": {
#                 "statuses": [
#                     {
#                         "code": "ProvisioningState/Unavailable",
#                         "display_status": "Not Ready",
#                         "level": "Warning",
#                         "message": "VM status blob is found but not yet populated.",
#                         "time": "2025-04-14T04:23:08.000Z"
#                     }
#                 ],
#                 "vm_agent_version": "Unknown"
#             }
#         },
#         "location": "centralus",
#         "name": "demo-vm",
#         "network_profile": {
#             "network_interfaces": [
#                 {
#                     "id": "/subscriptions/00b0a591-c96c-4b2f-bf7e-0c04a300756d/resourceGroups/demo_resource_group/providers/Microsoft.Network/networkInterfaces/demo_network_interface",
#                     "name": "demo_network_interface",
#                     "primary": true,
#                     "properties": {
#                         "auxiliary_mode": "None",
#                         "auxiliary_sku": "None",
#                         "disable_tcp_state_tracking": false,
#                         "dns_settings": {
#                             "applied_dns_servers": [],
#                             "dns_servers": [],
#                             "internal_domain_name_suffix": "mm0yw0f4ngmudc4w43osupm0lc.gx.internal.cloudapp.net"
#                         },
#                         "enable_accelerated_networking": false,
#                         "enable_ip_forwarding": false,
#                         "etag": "W/\"4ec215cb-c57d-4292-85e0-b9530b8f52a7\"",
#                         "hosted_workloads": [],
#                         "id": "/subscriptions/00b0a591-c96c-4b2f-bf7e-0c04a300756d/resourceGroups/demo_resource_group/providers/Microsoft.Network/networkInterfaces/demo_network_interface",
#                         "ip_configurations": [
#                             {
#                                 "etag": "W/\"4ec215cb-c57d-4292-85e0-b9530b8f52a7\"",
#                                 "id": "/subscriptions/00b0a591-c96c-4b2f-bf7e-0c04a300756d/resourceGroups/demo_resource_group/providers/Microsoft.Network/networkInterfaces/demo_network_interface/ipConfigurations/ipconfig1",
#                                 "name": "ipconfig1",
#                                 "primary": true,
#                                 "private_ip_address": "10.0.1.4",
#                                 "private_ip_address_version": "IPv4",
#                                 "private_ip_allocation_method": "Dynamic",
#                                 "provisioning_state": "Succeeded",
#                                 "public_ip_address": {
#                                     "id": "/subscriptions/00b0a591-c96c-4b2f-bf7e-0c04a300756d/resourceGroups/demo_resource_group/providers/Microsoft.Network/publicIPAddresses/demo_public_ip",
#                                     "name": "demo_public_ip",
#                                     "properties": {
#                                         "id": "/subscriptions/00b0a591-c96c-4b2f-bf7e-0c04a300756d/resourceGroups/demo_resource_group/providers/Microsoft.Network/networkInterfaces/demo_network_interface/ipConfigurations/ipconfig1"
#                                     }
#                                 },
#                                 "subnet": {
#                                     "id": "/subscriptions/00b0a591-c96c-4b2f-bf7e-0c04a300756d/resourceGroups/demo_resource_group/providers/Microsoft.Network/virtualNetworks/aap_demo_vnet/subnets/demo_subnet"
#                                 },
#                                 "type": "Microsoft.Network/networkInterfaces/ipConfigurations"
#                             }
#                         ],
#                         "location": "centralus",
#                         "mac_address": "00-0D-3A-42-10-26",
#                         "name": "demo_network_interface",
#                         "nic_type": "Standard",
#                         "primary": true,
#                         "provisioning_state": "Succeeded",
#                         "resource_guid": "c1ffc353-2c3d-449f-809f-0a832c3f0332",
#                         "tap_configurations": [],
#                         "type": "Microsoft.Network/networkInterfaces",
#                         "virtual_machine": {
#                             "id": "/subscriptions/00b0a591-c96c-4b2f-bf7e-0c04a300756d/resourceGroups/demo_resource_group/providers/Microsoft.Compute/virtualMachines/demo-vm"
#                         },
#                         "vnet_encryption_supported": false
#                     }
#                 }
#             ]
#         },
#         "os_profile": {
#             "admin_username": "demo_admin_user",
#             "allow_extension_operations": true,
#             "computer_name": "demo-vm",
#             "require_guest_provision_signal": true,
#             "secrets": [],
#             "windows_configuration": {
#                 "enable_automatic_updates": true,
#                 "enable_vm_agent_platform_updates": true,
#                 "patch_settings": {
#                     "assessment_mode": "ImageDefault",
#                     "patch_mode": "AutomaticByOS"
#                 },
#                 "provision_vm_agent": true
#             }
#         },
#         "powerstate": "running",
#         "provisioning_state": "Succeeded",
#         "storage_profile": {
#             "data_disks": [],
#             "image_reference": {
#                 "exact_version": "20348.3561.250409",
#                 "offer": "WindowsServer",
#                 "publisher": "MicrosoftWindowsServer",
#                 "sku": "2022-Datacenter",
#                 "version": "20348.3561.250409"
#             },
#             "os_disk": {
#                 "caching": "ReadWrite",
#                 "create_option": "FromImage",
#                 "delete_option": "Detach",
#                 "disk_size_gb": 128,
#                 "managed_disk": {
#                     "id": "/subscriptions/00b0a591-c96c-4b2f-bf7e-0c04a300756d/resourceGroups/demo_resource_group/providers/Microsoft.Compute/disks/demo_os_disk",
#                     "storage_account_type": "Standard_LRS"
#                 },
#                 "name": "demo_os_disk",
#                 "os_type": "Windows"
#             }
#         },
#         "tags": null,
#         "time_created": "2025-04-14T04:21:47.238551Z",
#         "type": "Microsoft.Compute/virtualMachines",
#         "vm_id": "18bbe82d-ab8d-4758-89c1-ddff0d6ac3eb"
#     }
# }
