---
- name: Create CMDB entry for Azure host
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Simulate VM creation
      ansible.builtin.set_fact:
        instance:
          name: test-vm99
          managed_by: Ansible
          public_ip_address: 192.168.1.99

    - name: Register the newly-created VM instance
      servicenow.itsm.configuration_item:
        name: "{{ instance.name }}"
        sys_class_name: cmdb_ci_vm_instance
        ip_address: "{{ instance.public_ip_address }}"
        other:
          managed_by: "{{ instance.managed_by }}"
      register: result

    - name: Show sys_id
      ansible.builtin.debug:
        msg: "CMDB entry sys_id: {{ result.record }}"
...
